name: Run Tests

on:
  push:
    branches: '**'
  pull_request:
    branches: 'main'

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3

      - name: Install dependencies
        run: npm install

      - name: project info
        run: |
          echo "OS is ${{ runner.os }}"
          echo "Password is ${{ secrets.pwd }}"
          echo "The project name is ${ env.PROJECT_NAME }"

      - name: Run tests
        run: npm run test
